### ISSUE TITLE
Test cases for hicBuildMatrix

### ISSUE THREAD

**Issue by joachimwolff** [maxplanck-ie/HiCExplorer#104]
In hicBuildMatrix is a bug concerning the computation of the cut_intervals. I have a fix for this and the test case `test_buildMatrix.test_build_matrix` is running as it should. (It is not uploaded right now because I am uncertain if everything is fixed.) The test case `test_buildMatrix.test_build_matrix_rf` is still failing. The print out of the first ten intervals of the test data, read from `small_test_rf_matrix.h5` looks like it was created with a version which was having the bug. I want to verify how the test data should look like. 

To verify I have printed out the first ten elements of `test.cut_intervals` and `new.cut_intervals` of the test case `test_buildMatrix.test_build_matrix_rf`:

`('test.cut_intervals', [('chr2L', 0, 455, 43), ('chr2L', 455, 913, 88), ('chr2L', 913, 1371, 133), ('chr2L', 1371, 1829, 178), ('chr2L', 1829, 2287, 223), ('chr2L', 2287, 2745, 268), ('chr2L', 2745, 3203, 313), ('chr2L', 3203, 3661, 358), ('chr2L', 3661, 4119, 403), ('chr2L', 4119, 4577, 448)])`

The last element is always increasing by 45. This behaviour was a bug caused by a wrong initalization of the coverage list. Instead of a `0`-initalization of each element a `0, 1, 2, 3, ..., n` initalization was done. The maximum element within a coverage is now always `i * width_of_coverage` for `i in n`.  But here it looks like that it should be this way? The computed output with the fix is now:  

`('new.cut_intervals', [('chr2L', 0, 455, nan), ('chr2L', 455, 913, nan), ('chr2L', 913, 1371, nan), ('chr2L', 1371, 1829, nan), ('chr2L', 1829, 2287, nan), ('chr2L', 2287, 2745, nan), ('chr2L', 2745, 3203, nan), ('chr2L', 3203, 3661, nan), ('chr2L', 3661, 4119, nan), ('chr2L', 4119, 4577, nan)])
`

The question is now if you know how the 4th element of an interval should look like. The given test data is looking like the bug version and I am not sure what the correct values should be. 

Thanks for your help!

**Comment by fidelram** [comment]
I think I have now corrected that (or at least it does not output `nan`). Apparently, the problem was caused in line https://github.com/maxplanck-ie/HiCExplorer/blob/python2to3/hicexplorer/hicBuildMatrix.py#L1092

I modified the function to receive a list and that seems to fix the problem. 

Also, I had to update the tests to reflect the new sorting of the chromosome names based on an OrderedDict to keep the order given by the alignment files. Double checking that the new test files are correct would be good.
