### ISSUE TITLE
TypeError in TAD_score

### ISSUE THREAD

**Issue by mzufferey** [maxplanck-ie/HiCExplorer#118]
Dear all,
I am trying to use HiCExplorer for calling TADs, but I encounter the following issue. I have a Hi-C matrix in Dekker's format, I first convert it into npz format using hicExport 

> hicExport -in HiC_matrix_colrow.txt.gz -o out_test_50.npz --inputFormat=dekker --outputFormat=npz

this works perfectly, but then I try to calculate the scores (with different parameters, here below just an example)

> hicFindTADs TAD_score -m out_test_50.npz --minDepth 150000 --maxDepth 300000 --step 50000 -o out_test_score_50   

the function hic_matrix.getRegionBinRange(chrom, left_start, left_start + 1)[0] raises the following error:

> TypeError: 'NoneType' object has no attribute '__getitem__'

do you have any idea of what can cause this error ??

thank you in advance

here below is the entire output:

INFO:hicFindTADs:removing diagonal values

binsize:        50000
command:        TAD_score
matrix: out_test_50.npz
maxDepth:       300000
minDepth:       150000
numberOfProcessors:     1
outFileName:    out_test_score_50
step:   50000
INFO:hicFindTADs:Computing z-score matrix...

processing chromosome chr6
*WARNING* File already exists out_test_score_50_zscore_matrix.h5
 Overwriting ...
INFO:hicFindTADs:Computing TAD-separation scores...

INFO:hicFindTADs:computing spectrum for window sizes between 3 (150000 bp)and 6 (300000 bp) at the following window sizes 1 [150000, 200000, 291421]

Traceback (most recent call last):
  File "/home/user/.local/bin/hicFindTADs", line 7, in <module>
    main()
  File "/home/user/.local/lib/python2.7/site-packages/hicexplorer/hicFindTADs.py", line 1202, in main
    chrom, chr_start, chr_end, matrix = compute_spectra_matrix(args)
  File "/home/user/.local/lib/python2.7/site-packages/hicexplorer/hicFindTADs.py", line 1013, in compute_spectra_matrix
    res = map(func, TASKS)
  File "/home/user/.local/lib/python2.7/site-packages/hicexplorer/hicFindTADs.py", line 255, in compute_matrix_wrapper
    return compute_matrix(*args)
  File "/home/user/.local/lib/python2.7/site-packages/hicexplorer/hicFindTADs.py", line 299, in compute_matrix
    mult_matrix = [get_cut_weight(hic_ma, cut, depth, return_mean=True) for depth in incremental_step]
  File "/home/user/.local/lib/python2.7/site-packages/hicexplorer/hicFindTADs.py", line 222, in get_cut_weight
    left_idx, right_idx = get_idx_of_bins_at_given_distance(hic_matrix, cut, window_len)
  File "/home/user/.local/lib/python2.7/site-packages/hicexplorer/hicFindTADs.py", line 204, in get_idx_of_bins_at_given_distance
    left_idx = hic_matrix.getRegionBinRange(chrom, left_start, left_start + 1)[0]
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by joachimwolff** [comment]
Dear mzufferey,

I can try to reproduce it and investigate what is going wrong. Is it possible for you to send me a small example input matrix which is causing this error? 

Thanks a lot,

Joachim

**Comment by mzufferey** [comment]
Dear Joachim, 
Thank you for your quick reply. I also continued to investigate in the meantime by running each line of the code step by step. And I found that one of the issue when using the Dekker format might be the following line:

>     left_start = max(0, cut_start - window_len)

indeed, as it is written in the HiCMatrix.py file, the Dekker format is as follows

>        for example 'bin1000000|dm3|chr4:1-50001'

so as it is 1-based, when left_start is 0, the following line raises the error

>        hic_matrix.getRegionBinRange(chrom, left_start, left_start + 1)[0]

as (if I understood correctly) the function 

> hic_matrix.getRegionBinRange(chrom, left_start, left_start + 1)

returns "None" because no bin overlapping the 0 position is found in the interval_trees, and so the use of "[0]" causes the error indicated in my previous message.

So I try to tackle this issue by changing the row and column headers of the Dekker format to make them 0-based, i.e. the first bin is 0-50000 instead of 1-50001.
But is it ok to change from 1-based to 0-based ? or does it impact the next part of the program or the TAD calling ?

Then I try to launch TAD_score again. It works, but with the following warning (I don't know if it is normal ?)

>  /usr/lib64/python2.7/site-packages/scipy/sparse/base.py:470: RuntimeWarning: divide by zero encountered in true_divide
  return self.astype(np.float_)._mul_scalar(1./other)

Despite the warning, all the needed files are generated, and I can then call the find_TADs tool.
It seems to work, but again with a warning (is it expected?)

>    /usr/lib64/python2.7/site-packages/scipy/stats/stats.py:4938: RuntimeWarning: invalid value encountered in double_scalars
        z = (s - expected) / np.sqrt(n1*n2*(n1+n2+1)/12.0)
    /home/user/.local/lib/python2.7/site-packages/hicexplorer/hicFindTADs.py:1136: RuntimeWarning: invalid value encountered in greater
      pvalues[pvalues > 1] = 1

The program finishes properly, however, it only found zero TAD (I try the default delta values and p-values as well as less stringent ones).

Maybe I used "bad" input data or I made bad choices for the parameters used in TAD_score...

You can find the files I used here: https://github.com/mzufferey/tmp_data
- Cmap_mapq30_diffrag_intrachr6_bw50kb_subsample_rep3_ICE_matrix_dekker.txt.gz [the "normal" 1-based Hi-C matrix in Dekker format]
- Cmap_mapq30_diffrag_intrachr6_bw50kb_subsample_rep3_ICE_matrix_dekker_zero.txt.gz [the 0-based Hi-C matrix in Dekker format]

(I used the hicExport with  --inputFormat=dekker --outputFormat=npz to convert them in npz format, and the resulting npz files as input for TAD_score)


Any help will be greatly appreciated !

Best regards,

Marie

**Comment by joachimwolff** [comment]
Dear Marie,

concerning the dekker format issue, I need more time to investigate this. It is quite old code, to quote Fidel in #116: "What I call dekker format are the matrices produced by Job Dekker about 2-3 years ago. I don't know what are they using now." Maybe the format has changed in the meantime, I will come back to you as soon as I know what is going on.

The reason that you did not found any TADs with hicFindTADs is likely to be caused by our used multiple testing correction. The current version uses the Bonferroni correction which is very strict. If you set the p-value to 1 you will probably see many TADs. These will be a bit meaningless but you can see that it is working in general. In the next release we add the false discovery rate and a 'None' option and I think these two more options will give you the ability to get meaningful TADs. 

I hope I was able to help you a bit,

Joachim

**Comment by mzufferey** [comment]
Many thanks for your reply ! So, I will try with different p-value thresholds and visualize the predicted domains in order to find a good trade-off...
Thanking you again for your responsiveness and best regards,
Marie
