### ISSUE TITLE
Get matrix with masked bins as nans

### ISSUE THREAD

**Issue by apaytuvi** [maxplanck-ie/HiCExplorer#128]
Hi,

I have `.h5` norm matrices but I'd like to see the masked bins as `nans` in the `python` console. Is that possible?

Thanks,
A.

**Comment by joachimwolff** [comment]
Dear apaytuvi,

I am not sure if I understand correctly what you want to do. We store nan bins in the variable `nan_bins`:
```
>>> from hicexplorer import HiCMatrix as hm
>>> hic = hm.hiCMatrix(matrixFile="matrix.h5")
>>> hic.nan_bins
array([   5,   23,   24,   36,   49,   50,   53,   54,   59,   75,   87,
        125,  151,  152,  153,  154,  155,  156,  157,  159,  160, 1080,
       1111, 1125, 1126, 1127, 1128, 1129, 1134, 1142, 1147, 1154, 1162])
```
If you want to have the masked bins in the matrix visible you have to call:
```
>>> hic.restoreMaskedBins()
```
But this step is done automatically at the time you load the h5 matrix.

Another interpretation of your question is to set the masked bins based on the indices from `nan_bins` explicitly to `np.nan`:
```
>>> import numpy as np
>>> matrix_array = hic.matrix.toarray().astype(float)
>>> matrix_array[hic.nan_bins, :] = np.nan
>>> matrix_array[:, hic.nan_bins] = np.nan
```
Be careful here, the call of `toarray()` creates a dense matrix. 

I hope I could help you. Please ask again if I misunderstood your question or could not answer your question.

Best,

Joachim

**Comment by apaytuvi** [comment]
I's very OK, thanks!
