### ISSUE TITLE
TADs and subTADs

### ISSUE THREAD

**Issue by apaytuvi** [maxplanck-ie/HiCExplorer#130]
I'd like to differentiate TADs (clear TADs, strong boundaries) from those more weaker TAD boundaries. How can I do that? Which value or thresholds should I set?

Thanks.

**Comment by fidelram** [comment]
Unfortunately, the TAD scores of boundaries, when sorted and plotted do not show any clear distinction that can be useful to separate strong vs week boundaries. 

You will need to decide on a threshold that works for your data by looking at the values on a test case where you manually annotate the boundaries.

**Comment by apaytuvi** [comment]
Thanks @fidelram
