### ISSUE TITLE
No module named hicPlotTADs_multit

### ISSUE THREAD

**Issue by yulijia** [maxplanck-ie/HiCExplorer#26]
Hello,
I have installed HiCExplorer and run the demo follow the [mES-HiC_analysis document](http://hicexplorer.readthedocs.org/en/latest/content/mES-HiC_analysis.html).

When I using `hicPlotTADs` to plot TAD domain, it reports an error **No module named hicPlotTADs_multit**

```bash
[yulj@ln01 yulj]$ hicPlotTADs --tracks tracks.ini --region chr1:1,000,000-2,000,000  -o tads.pdf
Traceback (most recent call last):
  File "/home/yulj/bin/hicPlotTADs", line 4, in <module>
    from hicexplorer.hicPlotTADs_multit import main
ImportError: No module named hicPlotTADs_multit
```

I didn't find any module named `hicPlotTADs_multit` in the library `lib/python2.7/site-packages/hicexplorer `. Could any one know how to fix the bug?
Should I using other module name (for example `hicPlotTADs`) to in lieu of `hicPlotTADs_multit` ?

I really do the test,  copy `hicPlotTADs.py` and `hicPlotTADs.pyc` to `hicPlotTADs_multit.py` and `hicPlotTADs_multit.pyc`  in the same library.

However, it reports another error:

```bash
[yulj@ln01 yulj]$ hicPlotTADs --tracks tracks.ini --BED TADs/marks_et-al_TADs_20kb-Bins_boundaries.bed  -o tads.pdf
{'x-axis': True, 'section_name': '1. [x-axis]'}
{'colormap': 'RdYlBu_r', 'title': 'Hi-C', 'file_type': 'hic_matrix', 'transform': 'log1p', 'depth': 1000000, 'section_name': '2. [hic track]', 'file': 'hiCmatrix/replicateMerged.Corrected-100bins.npz'}
Number of poor regions to remove: 2157
{'chr7': 147, 'chr6': 110, 'chr5': 104, 'chr4': 150, 'chr3': 127, 'chr2': 146, 'chr1': 142, 'chrY': 14, 'chr9': 71, 'chr8': 92, 'chr13': 80, 'chr12': 115, 'chr11': 79, 'chr10': 107, 'chr17': 70, 'chr16': 81, 'chr15': 71, 'chr14': 124, 'chr19': 51, 'chr18': 74, 'chrX': 202}
found existing 2157 nan bins that will be included for masking 
WARNING: bin size is not homogeneous. Median 190000
time initializing tracks
4.28803610802
saving tads.pdf_chr1:9975000-9975001'
Figure size in cm is 40 x 19.72. Dpi is set to 72
setting min, max values for track 2. [hic track] to: 1.0, 1.0
time before saving
1450667345.01
saving tads.pdf_chr1:9975000-9975001
Traceback (most recent call last):
  File "/home/yulj/bin/hicPlotTADs", line 7, in <module>
    main()
  File "/home/yulj/lib/python2.7/site-packages/hicexplorer/hicPlotTADs_multit.py", line 316, in main
    trp.plot(file_name, chrom, start, end, title=args.title)
  File "/home/yulj/lib/python2.7/site-packages/hicexplorer/trackPlot.py", line 186, in plot
    fig.savefig(file_name, dpi=self.dpi, transparent=False)
  File "/home/yulj/anaconda2/lib/python2.7/site-packages/matplotlib/figure.py", line 1565, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/home/yulj/anaconda2/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2139, in print_figure
    canvas = self._get_output_canvas(format)
  File "/home/yulj/anaconda2/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2079, in _get_output_canvas
    '%s.' % (format, ', '.join(formats)))
ValueError: Format "pdf_chr1:9975000-9975001" is not supported.
```

It seems that the program cannot generate the correct output file name.

How to fix the problem I have told above?

Hope to receive your feedback.

Thanks,
Lijia

**Comment by fidelram** [comment]
Thanks for letting us know about the problem with the unreferenced library. As you rightly suspected, the simple renaming of the file work.

Regarding your second problem, this is caused because of the prefix that you are using to save your files which contains a .pdf. When the image wants to be saved, the interpreter appends the region to the prefix and then gets confused with the file ending which not a valid format.

To solve your problem, simply change `-o tads.pdf` to simple `-o tads`. The disadvantage is that the plots will be saved as .png
