### ISSUE TITLE
Add testing

### ISSUE THREAD

**Issue by vivekbhr** [maxplanck-ie/HiCExplorer#36]
add a test to call significant minimas so that we can avoid the delta threshold.

**Comment by fidelram** [comment]
I added test data for hicPlotTads, maybe this can be used for a test.

**Comment by vivekbhr** [comment]
This testing part was for the statistical testing during the TAD calling..

**Comment by vivekbhr** [comment]
I will close this now after pull #63 . Testing the zscore-pvalues still remain for mammalian data for now
