### ISSUE TITLE
Wrong labels on scale bar for HiC heatmap

### ISSUE THREAD

**Issue by vivekbhr** [maxplanck-ie/HiCExplorer#47]
The scalebar for hicPlotTADs is wrong..

```
HicExplorer Version 1.3.
MatplotLib Version 1.4.3
```

**Comment by vivekbhr** [comment]
Update to matplotlib version 1.5 fixed it...

**Comment by fidelram** [comment]
I updated the setup.py to require a version of matplotlib that is at least 1.5.3
