### ISSUE TITLE
hicPlotMatrix strips | character from identifiers

### ISSUE THREAD

**Issue by edgreen72** [maxplanck-ie/HiCExplorer#56]
> hicPlotMatrix with --region gi|568336006|gb|CM000680.2|
results in Chromosome name gi568336006gbCM0006802 in --region not in matrix

There seems to be no way to escape the pipe ("|") character in an ID. I suppose there is some internal munging that is removing the pipe character, even escaped, from an ID.

**Comment by fidelram** [comment]
By default, the following characters were being are removed `,.;|!{}()`. Now only `,;!` are removed.
