### ISSUE TITLE
hicPlotMatrix argument list typo

### ISSUE THREAD

**Issue by edgreen72** [maxplanck-ie/HiCExplorer#57]
hicPlotMatrix, without arguments, gives this help:
usage: hicPlotMatrix [-h] --matrix MATRIX [--title TITLE]
                     [--scoreName SCORENAME] --outFileName OUTFILENAME
                     [--perChromosome] [--clearMaskedBins]
                     [--whatToShow {heatmap,3D,both}]
                     [--chromosomeOrder CHROMOSOMEORDER [CHROMOSOMEORDER ...]]
                     [--region REGION] [--region2 REGION2] [--log1p] [--log]
                     [--colorMap COLORMAP] [--vMin VMIN] [--vMax VMAX]
                     [--zMax ZMAX] [--dpi DPI] [--version]
hicPlotMatrix: error: argument --matrix/-m is required

The correct switch for the matrix should be -m, not -h (I think).

**Comment by fidelram** [comment]
This output is fine. The underlying python module that processes the program arguments adds [-h] which means `help` before anything else. Normally other arguments have a long and short version, for example `--matrix` vs `-m`, but without arguments just the long version is printed. 

This happens with all HiCExplorer programs.
