### ISSUE TITLE
enriched contacts

### ISSUE THREAD

**Issue by apaytuvi** [maxplanck-ie/HiCExplorer#87]
I am interested in finding enriched contacts, for instance bins with z-scores > than 3. Specially, I want to identify enriched contacts, intra- and inter-chromosome. For this purpose, I think I should compute z-scores considering only on one hand intra-chromosome bins and on the other hand inter-chromosome bins, right?

Is `hicExplorer` able to do so?

Thank you,
A.

**Comment by fidelram** [comment]
you have two options, either you compute the observed vs. expected ratio or you compute z-scores. Both methods are available as part of hicFindEnriched contacts.

**Comment by apaytuvi** [comment]
Good, thank you for your time, @fidelram !
