### ISSUE TITLE
Fractal/melt polymers in plot distance vs interaction

### ISSUE THREAD

**Issue by apaytuvi** [maxplanck-ie/HiCExplorer#98]
Is there a way to have plotted (using `hicPlotDistVsCounts`) the lines for distance/interaction for fractal and melted polymers? Something like this:

https://www.nature.com/article-assets/npg/nature/journal/v516/n7531/images/nature13833-sf2.jpg

Thank you very much!

**Comment by fidelram** [comment]
Actually is not possible. You will need to modify the code to add the lines that you want.

**Comment by apaytuvi** [comment]
@fidelram  I ended up modifying `hicPlotDistVsCounts` code, normalizing matrices in a way that they sum 1. Then, I plot fractal and melt models using `P(c) ~ c^-1` and `P(c) ~ c^-3/2`.
